apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.security.serverSecretKey }}
  server-secret-key: {{ .Values.security.serverSecretKey | b64enc }}
  {{- else }}
  server-secret-key: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
  {{- if .Values.security.hmacSecret }}
  hmac-secret: {{ .Values.security.hmacSecret | b64enc }}
  {{- else }}
  hmac-secret: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
